version: "3.8"

services:
  postgres:
    restart: always
    image: postgis/postgis
    container_name: pgsql
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure-password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - 8000:8000
    depends_on:
      - postgres