version: "3.8"

services:
  postgres:
    restart: always
    image: postgis/postgis
    container_name: pgsql
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile_CPU
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ${RAMP_HOME}:/RAMP_HOME
      - ${TRAINING_WORKSPACE}:/TRAINING_WORKSPACE
    depends_on:
      - redis
      - postgres