version: "3.9"

services:
  postgres:
    restart: always
    image: kartoza/postgis:12.0
    container_name: pgsql
    environment:
      - POSTGRES_DB=template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure-password
    ports:
      - "5434:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - 8000:8000
    depends_on:
      - postgres
      
volumes:
  postgres_data: 